# Generated by Django 4.1.5 on 2023-01-24 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country_code', models.CharField(max_length=3)),
                ('openweather_id', models.IntegerField(default=0, unique=True)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weather', serialize=False, to='weather.city')),
                ('temp', models.FloatField(default=0)),
                ('feels_like', models.FloatField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('desc_short', models.CharField(max_length=30, verbose_name='short description')),
                ('icon_name', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
    ]
