# Generated by Django 4.1.5 on 2023-01-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_delete_currentweather'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
