# Generated by Django 4.1.5 on 2023-01-24 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityStats',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='weather.city')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Статистика по городу',
                'verbose_name_plural': 'Статистика по городам',
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weather', serialize=False, to='weather.city')),
                ('temp', models.FloatField(default=0)),
                ('feels_like', models.FloatField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('desc_short', models.CharField(max_length=30, verbose_name='short description')),
                ('icon_name', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Прогноз',
                'verbose_name_plural': 'Прогнозы',
            },
        ),
        migrations.CreateModel(
            name='StatsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('weather.citystats',),
        ),
    ]
