# Generated by Django 4.1.5 on 2023-01-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_citystats_currentweather_statssummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='openweather_id',
            field=models.IntegerField(default=0),
        ),
    ]
