# Generated by Django 4.1.5 on 2023-01-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_city_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='desc_short_en',
            field=models.CharField(max_length=30, null=True, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='desc_short_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='short description'),
        ),
    ]
