# Generated by Django 4.1.5 on 2023-01-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_city_profile_country_profile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
