# Generated by Django 4.1.5 on 2023-01-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
