# Generated by Django 4.1.5 on 2023-01-25 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_history_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
