# Generated by Django 4.1.5 on 2023-01-25 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_city_openweather_id'),
        ('user', '0009_alter_favorite_city_name_alter_history_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
    ]
