# Generated by Django 4.1.5 on 2023-01-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_favorite_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='search_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
