# Generated by Django 4.1.5 on 2023-01-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_city_name_en_city_name_ru_and_more'),
        ('user', '0012_alter_history_search_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='city_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='city_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AddField(
            model_name='history',
            name='city_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AddField(
            model_name='history',
            name='city_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_en',
            field=models.CharField(default='Набережные Челны', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city_ru',
            field=models.CharField(default='Набережные Челны', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_en',
            field=models.CharField(default='Россия', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='profile',
            name='country_ru',
            field=models.CharField(default='Россия', max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
